### ISSUE TITLE
Permissions/blacklist.

### ISSUE THREAD

**Issue by erikcw** [playfire/django-debug-toolbar-user-panel#3]
It would be great to be able to exclude users who are members of a certain group from being able to be switched to.  I realize that this tool is only meant for trusted users, but there are still a few usernames in my organization that should never be switched to.  A blacklist using the django auth Group mechanism would work well I think.

**Comment by lamby** [comment]
> there are still a few usernames in my organization that should never be switched to

How come?

**Comment by lamby** [comment]
I'm going to wontfix this - it really is quite silly.
